Chore: Removing required installation id on client methods
inloco/incognia-ruby pull request #28
Opened 2024-08-14 20:40 UTC by lucaswilliamgomes

2024-08-14 20:43 UTC, lucaswilliamgomes commented on lib/incognia_api/api.rb
> +    def register_signup(address: nil, **opts)
During this transition period, we would return the API error, like:
![Screenshot from 2024-08-14 16-18-30](https://github.com/user-attachments/assets/46711278-cce7-4869-b73c-3c497225347b)
Wdyt?

2024-08-19 14:47 UTC, julianalucena requested changes

2024-08-19 14:47 UTC, julianalucena commented on spec/incognia_spec.rb
You renamed everything, as a side-effect the tests do not guarantee that the `installation_id` use case is working. Do you agree?

2024-08-19 14:47 UTC, julianalucena commented on lib/incognia_api/api.rb
> +    def register_signup(address: nil, **opts)
I think that's ok!

But I would let the method signature with `request_token` as a parameter, but with a default value (`nil`), to not break old usages. This way the lib is more elucidative on how we expect the client to use it.

The way it is now, it passes a wrong message to the client: you only need the account id for login and transactions, and for onboarding you don't need anything. Did you get my point?

2024-08-21 18:14 UTC, marcelscr commented
Mudflap is interested on using this feature :gogo:

2024-08-24 22:41 UTC, lucaswilliamgomes commented on spec/incognia_spec.rb
Yes, we just need to remember to remove these tests when the major release.
I did it [here](https://github.com/inloco/incognia-ruby/pull/28/commits/482fecf51b99dba016d9b27f54795212560fe37e).

2024-08-24 22:41 UTC, lucaswilliamgomes commented on lib/incognia_api/api.rb
> +    def register_signup(address: nil, **opts)
Yes, I agree with you, and I did it [here](https://github.com/inloco/incognia-ruby/pull/28/commits/482fecf51b99dba016d9b27f54795212560fe37e).

2024-08-26 12:49 UTC, julianalucena commented on spec/incognia_spec.rb
Nice. Thanks.

2024-08-26 12:50 UTC, julianalucena commented on lib/incognia_api/api.rb
> +    def register_signup(address: nil, **opts)
Nice, Lucs!

2024-08-26 13:01 UTC, julianalucena reviewed
Some suggestions regarding received parameters that I think will make code more readable and will require less changes when `request_token` starts to be required.

2024-08-26 13:01 UTC, julianalucena commented on lib/incognia_api/api.rb
>        params.merge!(address&.to_hash) if address
```suggestion
      params = { request_token: request_token }.compact
      params.merge!(opts)
      params.merge!(address&.to_hash) if address
```

2024-08-26 17:22 UTC, julianalucena approved these changes

2024-08-26 23:16 UTC, merged